import { Locale } from "../../shared/copy";

export function getDevCopy(locale: Locale) {
  if (locale === "ko") {
    return {
      title: "개발자 만세력 검증",
      lead: "입력값별 만세력, 대운, 신살·길성 결과를 한 화면에서 검토합니다.",
      serviceLink: "서비스 화면",
      mainHome: "메인 홈",
      languageLabel: "언어",
      koreanOption: "한국어",
      apiReady: "정상 연결",
      apiWaiting: "연결 대기",
      inputTitle: "검증 입력",
      inputLead: "사용자 입력과 같은 형식으로 넣고, 계산 결과를 개발자용 검토 화면에서 확인합니다.",
      submit: "만세력 보기",
      loading: "만세력 계산 중...",
      resultTitle: "만세력 검증 결과",
      resultLead: "사주 원국, 보정 시간, 대운, 신살·길성을 나눠서 빠르게 점검할 수 있게 정리했습니다.",
      noResult: "아직 검증 결과가 없습니다. 왼쪽 입력 폼에서 만세력을 조회해 주세요.",
      pipeline: "파이프라인 상태",
      llmDiagnostics: "LLM 진단",
      finalProvider: "최종 제공자",
      configuredProvider: "설정 제공자",
      fallbackReason: "Fallback 이유",
      responseId: "응답 ID",
      promptVersion: "프롬프트 버전",
      payloadChars: "Payload 길이",
      durationMs: "소요 시간",
      validationIssues: "검증 이슈",
      attemptLogs: "시도 기록",
      attempt: "시도",
      mode: "모드",
      tokenBudget: "토큰 한도",
      outputChars: "출력 길이",
      outputExcerpt: "출력 미리보기",
      error: "오류",
      none: "없음",
      checkpoints: "체크포인트",
      requestEcho: "입력 echo",
      basic: "기본 정보",
      correctedTime: "보정 시각",
      region: "지역",
      dayMaster: "일간",
      grade: "내부 등급",
      pillars: "사주 4주",
      manseTable: "만세력 표",
      elements: "오행 / 십성 분석",
      luckCycles: "대운",
      supplementary: "보조 위치",
      specialStars: "신살 / 길성",
      activeStarsTitle: "사주풀이 반영 신살 / 길성",
      activeStarsLead: "현재 입력값에서 실제로 매칭되어 사주풀이에 참고되는 항목만 보여줍니다.",
      totalActive: "활성 전체",
      activeAuspicious: "활성 길성",
      activeSinsal: "활성 신살",
      auspicious: "길성",
      sinsal: "신살",
      coreScope: "기본 세트",
      expandedScope: "확장 세트",
      optionalScope: "옵션 세트",
      starLabel: "항목",
      tier: "등급",
      category: "분류",
      status: "상태",
      method: "메서드",
      weight: "가중치",
      starCount: "매칭 수",
      usage: "해석 포인트",
      basis: "기준",
      rule: "규칙",
      anchor: "기준값",
      target: "목표값",
      matches: "매칭 위치",
      keywords: "키워드",
      noteLabel: "메모",
      activeState: "활성",
      inactiveState: "비활성",
      inactive: "해당 없음",
      noActiveStars: "현재 입력값에서 반영되는 신살 / 길성이 없습니다.",
      year: "연주",
      month: "월주",
      day: "일주",
      time: "시주",
      count: "개수",
      ratio: "비율",
      direction: "방향",
      exactAge: "정밀 시작 나이",
      preciseAge: "표시용 시작 나이 기준",
      boundary: "입운 경계",
      startAge: "시작 나이",
      period: "구간",
      ganZhi: "간지",
      rawJson: "표시용 JSON",
      noLuckCycles: "출생 시간을 모름으로 둔 경우 대운은 비활성화됩니다.",
    };
  }

  return {
    title: "Developer manse verification",
    lead: "Review manse, luck-cycle, and special-star output for each birth profile in one place.",
    serviceLink: "Service screen",
    mainHome: "Main home",
    languageLabel: "Language",
    koreanOption: "Korean",
    apiReady: "Connected",
    apiWaiting: "Waiting",
    inputTitle: "Verification input",
    inputLead: "Use the same input format as the service screen and inspect the result in a developer review layout.",
    submit: "Inspect manse",
    loading: "Calculating manse...",
    resultTitle: "Manse verification result",
    resultLead: "Pillars, time correction, luck cycles, and special stars are separated for quick review.",
    noResult: "No verification result yet. Submit the form on the left to inspect a manse result.",
    pipeline: "Pipeline",
    llmDiagnostics: "LLM diagnostics",
    finalProvider: "Final provider",
    configuredProvider: "Configured provider",
    fallbackReason: "Fallback reason",
    responseId: "Response ID",
    promptVersion: "Prompt version",
    payloadChars: "Payload size",
    durationMs: "Duration",
    validationIssues: "Validation issues",
    attemptLogs: "Attempt log",
    attempt: "Attempt",
    mode: "Mode",
    tokenBudget: "Token budget",
    outputChars: "Output size",
    outputExcerpt: "Output preview",
    error: "Error",
    none: "None",
    checkpoints: "Checkpoints",
    requestEcho: "Request echo",
    basic: "Basic info",
    correctedTime: "Corrected time",
    region: "Region",
    dayMaster: "Day master",
    grade: "Internal grade",
    pillars: "Four pillars",
    manseTable: "Manse table",
    elements: "Elements / ten-god analysis",
    luckCycles: "Luck cycles",
    supplementary: "Supplementary positions",
    specialStars: "Special stars",
    activeStarsTitle: "Interpretation stars",
    activeStarsLead: "Show only the stars matched by the current input and used for interpretation review.",
    totalActive: "Total active",
    activeAuspicious: "Active auspicious",
    activeSinsal: "Active shinsal",
    auspicious: "Auspicious",
    sinsal: "Shinsal",
    coreScope: "Core set",
    expandedScope: "Expanded set",
    optionalScope: "Optional set",
    starLabel: "Star",
    tier: "Tier",
    category: "Category",
    status: "Status",
    method: "Method",
    weight: "Weight",
    starCount: "Matches",
    usage: "Interpretation",
    basis: "Basis",
    rule: "Rule",
    anchor: "Anchor",
    target: "Targets",
    matches: "Matched pillars",
    keywords: "Keywords",
    noteLabel: "Note",
    activeState: "Active",
    inactiveState: "Inactive",
    inactive: "No match",
    noActiveStars: "No interpretation stars are active for this input.",
    year: "Year",
    month: "Month",
    day: "Day",
    time: "Time",
    count: "Count",
    ratio: "Ratio",
    direction: "Direction",
    exactAge: "Exact start age",
    preciseAge: "Display-age basis",
    boundary: "Boundary",
    startAge: "Start age",
    period: "Period",
    ganZhi: "Ganji",
    rawJson: "Display JSON",
    noLuckCycles: "Luck cycles are disabled when birth time is marked as unknown.",
  };
}
